const fs = require('fs');
let code = fs.readFileSync('/app/applet/App.tsx', 'utf8');

code = code.replace(
  '    name: "Ed Vocke",\n    image: "/ed.png",\n    role: "Chief Technology Officer",\n    paragraphs: [\n      "Ed Vocke is Chief Technology Officer at Equitable Labs, building federated learning infrastructure that lets financial institutions collaborate on fraud detection without compromising customer privacy. His career is defined by a single conviction: privacy and performance are not trade-offs but design requirements.",\n      "He has spent over a decade making that principle real, beginning in 2015 with early work on Recursive Neural Networks utilizing DeepMind. A published IEEE author on privacy-preserving technologies, he was selected for the United Nations AI Trust and Reimagination Program.",\n      "Ed extends this work through teaching and advisory practice. As an AI Instructor at the Milwaukee School of Engineering Center for Professional Education and founder of the AI advisory firm Superior Communications, he helps governments, nonprofits, and private industry move from AI ambition to responsible implementation. He has served as a panelist at UWEBC on AI governance and ethical AI use.",\n      "Ed\'s long-term focus centers on the communities most often excluded from these conversations. He works to ensure that advances in automated decision-making expand opportunity rather than entrench inequality, so underserved populations aren\'t left behind as the digital economy accelerates."\n    ]',
  '    name: "Ed Vocke",\n    image: "/ed.png",\n    role: "Chief Technology Officer",\n    paragraphs: [\n      "Ed Vocke is Chief Technology Officer at Equitable Labs, building federated learning infrastructure that lets financial institutions collaborate on fraud detection without compromising customer privacy. He works across engineering, compliance, and product teams to build infrastructure that supports fair, reliable automated decision-making while protecting the people that infrastructure is meant to serve.",\n      "Ed brings over a decade of expertise in machine learning and privacy tech. An early adopter of deep learning, his applied work started in 2015 by modifying and training character-level recurrent neural networks on specialized datasets. He is a published IEEE author on privacy-preserving technologies and was selected for the United Nations Development Programme\'s AI Trust and Safety Re-imagination Programme, an initiative bringing together practitioners to address emerging risks in AI deployment.",\n      "Ed extends this work through teaching and advisory practice. As an AI Instructor at the Milwaukee School of Engineering Center for Professional Education and founder of the AI advisory firm Superior Communications, he helps governments, nonprofits, and private industry move from AI ambition to responsible implementation. He has served as a panelist at University of Wisconsin E-Business Consortium on AI governance and ethical AI use.",\n      "Ed\'s long-term focus is on the communities most often left out of AI\'s design conversations. He works to ensure that automated decision-making expands opportunity rather than entrenches inequality—treating code as a tool for rebuilding trust and democratic participation in systems that too often exclude the people they claim to serve."\n    ]'
);

fs.writeFileSync('/app/applet/App.tsx', code);
console.log("App.tsx updated.");
